### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by nafisa20** [fac22/week3-MMC#40]
I'm unable to log in and was wondering whether this worked locally for you all and if not to maybe look at the errors.

Also wanted to mention that if a user isn't able to log in that you could send some html to reflect this like a 'user not found' message and you could do the same on your sign up page
https://github.com/fac22/week3-MMC/blob/a33036b9c03538a6c6ee86b44c8203939ecbad51/routes/logIn.js#L50

**Comment by Alisyad9** [comment]
Thanks for the comment @nafisa20, the issue was caused by the secret_cookie not configured on heroku. it should now work fine. you can login.
